### ISSUE TITLE
Payout is skipped when player wins

### ISSUE THREAD

**Issue by s-fleck** [root676/G08_python_for_geosciences#3]
Springt direkt von 
To you want to bet on another option? (y/n): 
zu
Do you want to play another round? (y/n) 

ohne gewinne/verluste anzuzeigen.

Ist mir noch nicht klaar womit das im detail zusammenhaengt...

**Comment by Coldrunner** [comment]
Wann passiert das? - und bei welchem depot jetzt?
Also bei mir gehts - hab jetzt noch den bug mit den nicht angegebenen gewinnen gelöst.
probiers bitte nochmal-> grundsätzlich: du kannst mehrere wetten abgeben in einer runde bevor das roulette gedreht wird. daher fragt er in einer runde ob du noch weitere wetten abgeben möchtest. nach der runde, fragt er aber ob du weiter spielen kannst - also eine weitere runde.

**Comment by root676** [comment]
Die Gewinne werden nun zwar bei mir angezeigt, dafür habe ich Probleme mit Rot/Schwarz, gerade/ungerade. Ich habe soeben eine Runde mit 1000€ Einsatz gespielt. Mein Satz: 200 auf gerade, 200 auf ungerade, 200 auf Rot, 200 auf schwarz. Es wird die Zahl 15 gezogen (ungerade und Schwarz). Ergebnis: 

_The roulette stopped at number 15 !
You won 0 Euro and lost 800.0 Euro!
You now have 200.0 Euro in total._

Eigentlich sollte ich mit 400 gewonnenen, 400 verlorenen und 200 ungesetzten Euros = 600€ vom Tisch gehen. Er gesteht hingegen den Gewinn nicht zu und lässt mich mit 200 stehen.

**Comment by Coldrunner** [comment]
ah danke red/black war vorher groß geschrieben. aber der inout vom user wurde auf kleinschreibung gesetzt damit Black==black nicht korrekt; bei even/odd wars intern als True/False was bei True==even auch nicht geht:
    def getcolor(self):
        if self.roulette_number in [1,3,5,7,9,12,14,16,18,19,21,23,25,27,30,32,34,36]:
            return 'red'
        elif self.roulette_number == 0:
            return 'No color (Zero)'
        else:
            return 'black'
