### ISSUE TITLE
Zero-case

### ISSUE THREAD

**Issue by root676** [root676/G08_python_for_geosciences#5]
Mir ist noch aufgefallen, dass folgender Fall noch nicht implementiert ist (zumindest hab ich es nicht entdecken können):

_When number zero comes then everybody loses unless they bet on zero._

Soweit ich das sehen kann ist der Zero-Case nur in folgendem Codeteil berücksichtigt, hat jedoch keine Referenz auf Geldwerte/Gewinn oder Verlustchancen.

```
   def getcolor(self):
        if self.roulette_number in [1,3,5,7,9,12,14,16,18,19,21,23,25,27,30,32,34,36]:
            return 'Red'
        elif self.roulette_number == 0:
            return 'No color (Zero)'
        else:
            return 'Black'
```

**Comment by Coldrunner** [comment]
Das ist indirekt implementiert - da in allen optionen die du sonst wählen kannst "0" nicht beinhalten. Daher wenn "0" kommt, kannst du nur gewinnen wenn du direkt darauf setzt.
Bei  even/odd muss es neben rot/schwarz ebenfalls explizit abgefragt werden:

```
def checkeven(self):
    if self.roulette_number == 0:
        return ''
    elif self.roulette_number % 2 > 0:
        return 'odd'
    else:
        return 'even'
```

**Comment by root676** [comment]
Wow, an das hab ich gar nicht gedacht!
