### ISSUE TITLE
Play nextround() without budget

### ISSUE THREAD

**Issue by root676** [root676/G08_python_for_geosciences#7]
Die Applikation fragt, wenn man sämtliches Geld verspielt hat (auch über mehrere Runden), ob man eine weitere Runde spielen mag.

**Comment by Coldrunner** [comment]
ok, hab mir eingebildet das ist schon abgeändert - kann ich mir gleich anschauen, bin grad beim bericht

**Comment by root676** [comment]
dachte ich auch, aber irgendwas haut da nicht hin. Ist mir nur grad aufgefallen als ich grad ein bissl Roulette gespielt hab... ;)
