### ISSUE TITLE
Programm Crasht bei vollem Einsatz von vorhandenem Geld

### ISSUE THREAD

**Issue by root676** [root676/G08_python_for_geosciences#8]

**Comment by Coldrunner** [comment]
ich bekomme keinen fehler

**Comment by Coldrunner** [comment]
kannst einen screenshot schicken?

**Comment by root676** [comment]
Nope, es crasht nicht direkt aber wird sofort beendet (commandline schließt sich ohne, dass angezeigt wird dass man kein Geld hat). Trat bei mir auch erst in Runde 3 auf. Vl. sollten wir das noch implementieren, dass angezeigt wird, dass man sein ganzes Geld grade verspielt hat und daher vom Tisch gehen muss.

**Comment by root676** [comment]
Könnte man mit `import time` und `time.sleep(3)` probieren, dann schließt er das Fenster nicht sofort.

**Comment by Coldrunner** [comment]
bei  mir steht vorher "Sorry - You have no money left to bet."
und danach weils ja beendet wird: "You are leaving the Rpulette table with 0.0 Euro"

bist du mit dem code up to date? weil das kann passiert sein bevor ich den bug #7 gelöst habe

**Comment by root676** [comment]
Arbeitest du im Pyscripter oder direkt in der python commandline? Ich bin mir sicher, dass das nur eine Eigenheit der Commandline ist. Pyscripter schließt sich ja nicht, wenn das Programm einen Run beendet. @codeversion: ich hab deinen Bugfix schon dabei.

**Comment by Coldrunner** [comment]
hab beides jetzt ausprobiert mit ein
![commandline](https://cloud.githubusercontent.com/assets/11662821/7105020/47d732ec-e104-11e4-8ecd-36dc9ba2cff8.PNG)
er runde:

**Comment by root676** [comment]
ok, ich sehe schon, es funktioniert eh. Mein Interpreter schließt sich nur zu schnell. ;)
