### ISSUE TITLE
What digit is the most frequent between the numbers 1 and 1000?

### ISSUE THREAD

**Issue by Coldrunner** [root676/G08_python_for_geosciences#9]
Bezüglich dem Code der hier drunter steht - Sollen wir tatsächlich dies Programm technisch umsetzen? oder einfach beantworten wie alle text fragen?
Bezüglich Lösung -> die sind ja logischerweise gleich verteilt.
Meiner Meinung nach hätte ich "0" gesagt aber auch nur wenn mit "0001","0002",...usw
gerechnet wird - in allen anderen Fällen gibt es keine Zahl die öfters vorkommt als alle anderen.
# What digit is the most frequent between the numbers 1 and 1000?
# mir fiel keine Numpy Lösung ein...

thousandlist = range(1,1001)
digitlist =[]
for element in thousandlist:
    for digit in str(element):
        digitlist.append(int(digit))

onetothousand_vector = np.array(digitlist)

plt.hist(onetothousand_vector, bins=10)
plt.show()

**Comment by root676** [comment]
Naja ich glaub schon dass wir es technisch umsetzen sollten: "Prove the solution of riddle row1 with a histogram." Sonst würde man riddle row1 ja nicht für die Lösung des gesamten Rätsels brauchen soweit ich das sehe. 
@ Lösung: wenn man die Zahlen von 1 bis 1000 anschaut, dann sind es (ohne vorangestellte Nullen) die Einser (genau 301 mal), die am häufigsten vorkommen.

**Comment by Coldrunner** [comment]
stimmt - hast recht! ok passt - wert wird auch direkt aus dem array herausgezogen. danke!
